version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps3-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: deps3-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
          - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
      - store_artifacts:
          path: build
      - run: #update build doc and readme
          name: update api
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
                git clone git@github.com:datavisyn/lineup.js.org.git
                cd lineup.js.org
                rm -rf "${CIRCLE_BRANCH}/"
                if [ "${CIRCLE_BRANCH}" == "develop" ] ; then
                  rm -rf ../build/docs
                fi
                mv ../build "${CIRCLE_BRANCH}"
                cp ../demo/* "${CIRCLE_BRANCH}/"
                git config user.email "samuel_gratzl@gmx.at"
                git config user.name "Samuel Gratzl"
                git add -A
                git commit -m "auto updating ${CIRCLE_BRANCH}" -m "trigger: ${CIRCLE_BUILD_URL}"
                git push origin master
            fi
  deploy:
    working_directory: ~/src
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps3-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: deps3-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
          - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: deploy
          command: npm run deploy
      - run: #update build doc and readme
          name: update api
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
                git clone git@github.com:datavisyn/lineup.js.org.git
                cd lineup.js.org
                rm -rf "${CIRCLE_BRANCH}/"
                if [ "${CIRCLE_BRANCH}" == "develop" ] ; then
                  rm -rf ../build/docs
                fi
                mv ../build "${CIRCLE_BRANCH}"
                cp ../demo/* "${CIRCLE_BRANCH}/"
                git config user.email "samuel_gratzl@gmx.at"
                git config user.name "Samuel Gratzl"
                git add -A
                git commit -m "auto updating ${CIRCLE_BRANCH}" -m "trigger: ${CIRCLE_BUILD_URL}"
                git push origin master
            fi

workflows:
  version: 2
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
      - deploy:
          filters:
            branches:
              only: master
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
